# -----------------------------------------------------
# Monitors (repris de ton ancienne config ML4W - HDR)
# Réglable au besoin avec `nwg-displays`.
# -----------------------------------------------------

monitorv2 {
    output = DP-1
    mode = 3440x1440@174.96
    position = 360x0
    scale = 1.0
    bitdepth = 10
    cm = hdr
}

monitorv2 {
    output = HDMI-A-1
    mode = 1920x1080@60
    position = 1120x1440
    scale = 1.0
}
